from building import Building
from city import City

Smithsonian = Building("Washington DC", 4)
Smithsonian.constructor()
Smithsonian.purchase("Fred")
Parthenon = Building("Tennessee", 3)
Parthenon.purchase("John")
Parthenon.constructor()
Belle_Meade = Building("Tennessee", 2)
Belle_Meade.purchase("Geraldine")
Belle_Meade.constructor()
Taj_Mahal = Building("India", 4)
Taj_Mahal.purchase("Ghandi")
Taj_Mahal.constructor()
Colosseum = Building("Rome", 2)
Colosseum.purchase("Hannah")
Colosseum.constructor()
new_building = Building("Alabama State Capital", 2)
new_building.constructor()
print(f'{new_building.address} was purchased by {new_building.designer} on {new_building.date_constructed} and has {new_building.stories} stories.')
gadsden = City("Gadsden","Sherman Guyton")
gadsden.add_building(Smithsonian)
gadsden.add_building(Parthenon)
gadsden.add_building(Taj_Mahal)
gadsden.add_building(Belle_Meade)
gadsden.add_building(Colosseum)
for building in gadsden.all_buildings:
    print(building)